/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'thesia-backend.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./thesia-backend.android-arm64.node')
          } else {
            nativeBinding = require('thesia-backend-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'thesia-backend.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./thesia-backend.android-arm-eabi.node')
          } else {
            nativeBinding = require('thesia-backend-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'thesia-backend.win32-x64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./thesia-backend.win32-x64-msvc.node')
          } else {
            nativeBinding = require('thesia-backend-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(
          join(__dirname, 'thesia-backend.win32-ia32-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./thesia-backend.win32-ia32-msvc.node')
          } else {
            nativeBinding = require('thesia-backend-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'thesia-backend.win32-arm64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./thesia-backend.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('thesia-backend-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'thesia-backend.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./thesia-backend.darwin-universal.node')
      } else {
        nativeBinding = require('thesia-backend-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'thesia-backend.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./thesia-backend.darwin-x64.node')
          } else {
            nativeBinding = require('thesia-backend-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'thesia-backend.darwin-arm64.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./thesia-backend.darwin-arm64.node')
          } else {
            nativeBinding = require('thesia-backend-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(join(__dirname, 'thesia-backend.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./thesia-backend.freebsd-x64.node')
      } else {
        nativeBinding = require('thesia-backend-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'thesia-backend.linux-x64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./thesia-backend.linux-x64-musl.node')
            } else {
              nativeBinding = require('thesia-backend-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'thesia-backend.linux-x64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./thesia-backend.linux-x64-gnu.node')
            } else {
              nativeBinding = require('thesia-backend-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'thesia-backend.linux-arm64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./thesia-backend.linux-arm64-musl.node')
            } else {
              nativeBinding = require('thesia-backend-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'thesia-backend.linux-arm64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./thesia-backend.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('thesia-backend-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'thesia-backend.linux-arm-musleabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./thesia-backend.linux-arm-musleabihf.node')
            } else {
              nativeBinding = require('thesia-backend-linux-arm-musleabihf')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'thesia-backend.linux-arm-gnueabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./thesia-backend.linux-arm-gnueabihf.node')
            } else {
              nativeBinding = require('thesia-backend-linux-arm-gnueabihf')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'riscv64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'thesia-backend.linux-riscv64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./thesia-backend.linux-riscv64-musl.node')
            } else {
              nativeBinding = require('thesia-backend-linux-riscv64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'thesia-backend.linux-riscv64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./thesia-backend.linux-riscv64-gnu.node')
            } else {
              nativeBinding = require('thesia-backend-linux-riscv64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 's390x':
        localFileExisted = existsSync(
          join(__dirname, 'thesia-backend.linux-s390x-gnu.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./thesia-backend.linux-s390x-gnu.node')
          } else {
            nativeBinding = require('thesia-backend-linux-s390x-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const { GuardClippingMode, FreqScale, init, addTracks, reloadTracks, removeTracks, applyTrackListChanges, getdBRange, setdBRange, setColormapLength, getSpecSetting, setSpecSetting, getCommonGuardClipping, setCommonGuardClipping, getCommonNormalize, setCommonNormalize, getSpectrogram, getWavImage, findIdByPath, getOverview, freqPosToHz, freqHzToPos, secondsToLabel, timeLabelToSeconds, hzToLabel, freqLabelToHz, getTimeAxisMarkers, getFreqAxisMarkers, getAmpAxisMarkers, getdBAxisMarkers, getMaxdB, getMindB, getMaxTrackHz, getLongestTrackLengthSec, getChannelCounts, getLengthSec, getSampleRate, getFormatInfo, getGlobalLUFS, getRMSdB, getMaxPeakdB, getGuardClipStats, getPath, getFileName, getColorMap, setVolumedB, setTrackPlayer, seekPlayer, pausePlayer, resumePlayer, getPlayerState } = nativeBinding

module.exports.GuardClippingMode = GuardClippingMode
module.exports.FreqScale = FreqScale
module.exports.init = init
module.exports.addTracks = addTracks
module.exports.reloadTracks = reloadTracks
module.exports.removeTracks = removeTracks
module.exports.applyTrackListChanges = applyTrackListChanges
module.exports.getdBRange = getdBRange
module.exports.setdBRange = setdBRange
module.exports.setColormapLength = setColormapLength
module.exports.getSpecSetting = getSpecSetting
module.exports.setSpecSetting = setSpecSetting
module.exports.getCommonGuardClipping = getCommonGuardClipping
module.exports.setCommonGuardClipping = setCommonGuardClipping
module.exports.getCommonNormalize = getCommonNormalize
module.exports.setCommonNormalize = setCommonNormalize
module.exports.getSpectrogram = getSpectrogram
module.exports.getWavImage = getWavImage
module.exports.findIdByPath = findIdByPath
module.exports.getOverview = getOverview
module.exports.freqPosToHz = freqPosToHz
module.exports.freqHzToPos = freqHzToPos
module.exports.secondsToLabel = secondsToLabel
module.exports.timeLabelToSeconds = timeLabelToSeconds
module.exports.hzToLabel = hzToLabel
module.exports.freqLabelToHz = freqLabelToHz
module.exports.getTimeAxisMarkers = getTimeAxisMarkers
module.exports.getFreqAxisMarkers = getFreqAxisMarkers
module.exports.getAmpAxisMarkers = getAmpAxisMarkers
module.exports.getdBAxisMarkers = getdBAxisMarkers
module.exports.getMaxdB = getMaxdB
module.exports.getMindB = getMindB
module.exports.getMaxTrackHz = getMaxTrackHz
module.exports.getLongestTrackLengthSec = getLongestTrackLengthSec
module.exports.getChannelCounts = getChannelCounts
module.exports.getLengthSec = getLengthSec
module.exports.getSampleRate = getSampleRate
module.exports.getFormatInfo = getFormatInfo
module.exports.getGlobalLUFS = getGlobalLUFS
module.exports.getRMSdB = getRMSdB
module.exports.getMaxPeakdB = getMaxPeakdB
module.exports.getGuardClipStats = getGuardClipStats
module.exports.getPath = getPath
module.exports.getFileName = getFileName
module.exports.getColorMap = getColorMap
module.exports.setVolumedB = setVolumedB
module.exports.setTrackPlayer = setTrackPlayer
module.exports.seekPlayer = seekPlayer
module.exports.pausePlayer = pausePlayer
module.exports.resumePlayer = resumePlayer
module.exports.getPlayerState = getPlayerState
